name: pr-checks

on:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  ARM_USE_OIDC: "true"
  ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
  TF_VAR_dev_ip: ${{ secrets.TF_VAR_dev_ip }}
  TF_VAR_pg_entra_admin_object_id: ${{ secrets.TF_VAR_pg_entra_admin_object_id }}
  TF_VAR_pg_entra_admin_upn: ${{ secrets.TF_VAR_pg_entra_admin_upn }}

defaults:
  run:
    working-directory: secure-workload

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: fmt
        run: terraform fmt -check -recursive

      - name: init
        run: terraform init

      - name: validate
        run: terraform validate

      - name: plan
        run: terraform plan -no-color -input=false

      - name: checkov
        run: |
          pip install checkov
          checkov -d . --soft-fail